feat: init and add sidebar
OneKonsole/web-service-frontend pull request #42
Opened 2023-11-14 21:08 UTC by wolozdeto

add main side bar and init tailwind, pages

2023-11-14 22:00 UTC, TeissierYannis requested changes
Très bien, j'ai proposé quelques modifications si ca te convient

2023-11-14 22:00 UTC, TeissierYannis commented on package.json
> +    "react-pro-sidebar": "0.6.0",
`pnpm uninstall react-pro-sidebar`
il me semble que tu ne l'utilises pas

2023-11-14 22:00 UTC, TeissierYannis commented on pnpm-lock.yaml
Ajouter au gitignore

2023-11-14 22:00 UTC, TeissierYannis commented on src/App.tsx
`<Suspense fallback={<div>Loading...</div>}>
            {useRoutes(routes)}
        </Suspense>`
        
        Il me semble que c'est en trop ca (juste avant la div)

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/account.svg
Ajouter a un dossier icons ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/billing.svg
Ajouter a un dossier icons ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/cluster.svg
Ajouter a un dossier icons ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/download.svg
Ajouter a un dossier icons ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/logo-full.svg
Ajouter a un dossier logo ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/logo-short.svg
Ajouter a un dossier logo ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/logout.svg
Ajouter a un dossier icons ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/monitor.svg
Ajouter a un dossier icons ?

2023-11-14 22:00 UTC, TeissierYannis commented on src/assets/order.svg
Ajouter a un dossier icons ?

2023-11-14 22:34 UTC, wolozdeto commented on package.json
> +    "react-pro-sidebar": "0.6.0",
bv merci

2023-11-14 22:36 UTC, wolozdeto commented on pnpm-lock.yaml
bv merci

2023-11-15 08:55 UTC, TeissierYannis approved these changes

2023-11-15 08:57 UTC, merged